name: django-app
provider: aws
flavor: ecs
version: 1

collections:
- name: test
  region: us-east-1
  base_domain: zzdjangoexample.cncsites.com
  account_id: "110600864631"
  environments:
  - name: staging
    environment_variables:
    - name: FOO
      value: bar